<?php

/**
 * Information architecture definitions for South Forsyth content planning.
 * This supports topical authority, internal linking, and future growth into a large local publishing platform.
 */

if (! defined('ABSPATH')) {
    exit;
}

if (! function_exists('southforsyth_get_information_architecture')) {
    function southforsyth_get_information_architecture()
    {
        return array(
            'home' => array(
                'title' => 'Home',
                'purpose' => 'Serve as the primary discovery hub for South Forsyth residents, visitors, and local businesses.',
                'audience' => 'Residents, visitors, new movers, and local businesses.',
                'url' => '/',
                'taxonomy' => 'Topic',
                'categories' => array('Community', 'Local Guide', 'Featured Content'),
                'tags' => array('south-forsyth', 'local-guide', 'community-homepage'),
                'custom_fields' => array('Hero headline', 'Featured guide cards', 'Primary CTA', 'Featured events', 'Editorial note'),
                'schema_opportunities' => array('WebSite', 'Organization', 'BreadcrumbList', 'LocalBusiness', 'Event'),
                'internal_links' => array('Things to Do', 'Weekend Guide', 'Restaurants', 'Schools', 'New Resident Guide'),
                'future_filters' => array('Location', 'Category', 'Audience', 'Season'),
                'related_pages' => array('Things To Do', 'Weekend Guide', 'Neighborhoods', 'Local News'),
                'sidebar_recommendations' => array('Featured events', 'New resident resources', 'Local business spotlight'),
                'seo_strategy' => 'Target high-intent local discovery terms while linking heavily to topical sections.',
                'ai_strategy' => 'Structure content as clear topical clusters with concise summaries, FAQs, and strong metadata.'
            ),
            'things-to-do' => array(
                'title' => 'Things To Do',
                'purpose' => 'Introduce the city as an enjoyable place to explore through experiences, outings, and day plans.',
                'audience' => 'Families, visitors, weekend planners, and local explorers.',
                'url' => '/things-to-do/',
                'taxonomy' => 'Experience',
                'categories' => array('Outdoors', 'Entertainment', 'Family Activities', 'Seasonal'),
                'tags' => array('weekend', 'family', 'local-favorites'),
                'custom_fields' => array('Activity type', 'Age range', 'Location', 'Cost', 'Best season'),
                'schema_opportunities' => array('ThingToDo', 'Event', 'Place'),
                'internal_links' => array('Parks', 'Trails', 'Playgrounds', 'Events', 'Weekend Guide'),
                'future_filters' => array('Budget', 'Age range', 'Indoor/Outdoor', 'Distance'),
                'related_pages' => array('Events', 'Parks', 'Family Activities', 'Weekend Guide'),
                'sidebar_recommendations' => array('Upcoming events', 'Best family trips', 'Nearby dining'),
                'seo_strategy' => 'Target “things to do in South Forsyth” and related long-tail local intent terms.',
                'ai_strategy' => 'Provide structured lists with clear summaries, map-friendly details, and recommended next steps.'
            ),
            'events' => array(
                'title' => 'Events',
                'purpose' => 'Help users stay up to date on events, fairs, markets, performances, and recurring community happenings.',
                'audience' => 'Residents, families, and visitors planning around the calendar.',
                'url' => '/events/',
                'taxonomy' => 'Calendar',
                'categories' => array('Community', 'Arts', 'Sports', 'Education', 'Seasonal'),
                'tags' => array('calendar', 'community-events', 'upcoming'),
                'custom_fields' => array('Event date', 'Time', 'Venue', 'Category', 'Admission'),
                'schema_opportunities' => array('Event', 'Offer', 'Place'),
                'internal_links' => array('Weekend Guide', 'Things To Do', 'Restaurants', 'Holiday Guides'),
                'future_filters' => array('Date', 'Category', 'Free/Paid', 'Neighborhood'),
                'related_pages' => array('Weekend Guide', 'Seasonal Guides', 'Holiday Guides', 'Local News'),
                'sidebar_recommendations' => array('Upcoming this weekend', 'Family events', 'Local business sponsors'),
                'seo_strategy' => 'Capture event-based searches with detailed event schema and seasonal landing pages.',
                'ai_strategy' => 'Use consistent event summaries, dates, and FAQs to improve discoverability in AI-powered search.'
            ),
            'weekend-guide' => array(
                'title' => 'Weekend Guide',
                'purpose' => 'Curate a practical weekend plan with food, parks, events, and activities for visitors and residents.',
                'audience' => 'Families, couples, weekend travelers, and casual local explorers.',
                'url' => '/weekend-guide/',
                'taxonomy' => 'Guide',
                'categories' => array('Weekend', 'Family', 'Dating', 'Outdoors'),
                'tags' => array('weekend-plan', 'local-guide', 'discover'),
                'custom_fields' => array('Best for', 'Duration', 'Weather dependency', 'Budget', 'Map links'),
                'schema_opportunities' => array('Article', 'HowTo', 'BreadcrumbList'),
                'internal_links' => array('Things To Do', 'Restaurants', 'Coffee Shops', 'Parks', 'Events'),
                'future_filters' => array('Budget', 'Family-friendly', 'Rainy day', 'Distance'),
                'related_pages' => array('Things To Do', 'Restaurants', 'Coffee Shops', 'Holiday Guides'),
                'sidebar_recommendations' => array('Weekend picks', 'Weather outlook', 'Nearby attractions'),
                'seo_strategy' => 'Target “weekend in South Forsyth” and guide-style keywords with rich internal linking.',
                'ai_strategy' => 'Format as a clear itinerary with short sections, bullets, and strong answer-oriented summaries.'
            ),
            'restaurants' => array(
                'title' => 'Restaurants',
                'purpose' => 'Present local dining options with useful details for food-focused discovery.',
                'audience' => 'Residents, parents, date-night planners, and visitors.',
                'url' => '/restaurants/',
                'taxonomy' => 'Dining',
                'categories' => array('Breakfast', 'Lunch', 'Dinner', 'Family', 'Date Night'),
                'tags' => array('dining', 'local-food', 'places-to-eat'),
                'custom_fields' => array('Cuisine', 'Price range', 'Hours', 'Reservations', 'Delivery'),
                'schema_opportunities' => array('LocalBusiness', 'Restaurant', 'Menu'),
                'internal_links' => array('Coffee Shops', 'Shopping', 'Events', 'Weekend Guide'),
                'future_filters' => array('Cuisine', 'Price', 'Neighborhood', 'Outdoor seating'),
                'related_pages' => array('Coffee Shops', 'Shopping', 'Weekend Guide', 'Neighborhoods'),
                'sidebar_recommendations' => array('Top picks', 'Brunch spots', 'Family-friendly dining'),
                'seo_strategy' => 'Capture restaurant-intent keywords and optimize each profile with structured data and local references.',
                'ai_strategy' => 'Provide concise descriptions, pricing cues, and quick answers to dining questions.'
            ),
            'coffee-shops' => array(
                'title' => 'Coffee Shops',
                'purpose' => 'Support local coffee discovery for work, study, and casual visits.',
                'audience' => 'Remote workers, students, and neighbors.',
                'url' => '/coffee-shops/',
                'taxonomy' => 'Dining',
                'categories' => array('Coffee', 'Workspace', 'Study', 'Brunch'),
                'tags' => array('coffee', 'remote-work', 'local-spot'),
                'custom_fields' => array('Wi-Fi', 'Parking', 'Hours', 'Pet-friendly', 'Seating'),
                'schema_opportunities' => array('LocalBusiness', 'CafeOrCoffeeShop'),
                'internal_links' => array('Restaurants', 'Weekend Guide', 'Work-friendly spaces'),
                'future_filters' => array('Wi-Fi', 'Pet-friendly', 'Drive-through', 'Neighborhood'),
                'related_pages' => array('Restaurants', 'Weekend Guide', 'Shopping'),
                'sidebar_recommendations' => array('Study spots', 'Best brunch pairings', 'Weekend plans'),
                'seo_strategy' => 'Target “coffee shop near me” and “best coffee in South Forsyth” style queries.',
                'ai_strategy' => 'Highlight practical details like Wi-Fi and seating to improve AI answer quality.'
            ),
            'parks' => array(
                'title' => 'Parks',
                'purpose' => 'Help users discover parks, playgrounds, family recreation, and open-space options.',
                'audience' => 'Parents, walkers, families, and visitors.',
                'url' => '/parks/',
                'taxonomy' => 'Place',
                'categories' => array('Parks', 'Recreation', 'Family', 'Outdoors'),
                'tags' => array('parks', 'playground', 'picnic'),
                'custom_fields' => array('Amenities', 'Parking', 'Restrooms', 'Dog-friendly', 'Open hours'),
                'schema_opportunities' => array('Park', 'Place', 'LocalBusiness'),
                'internal_links' => array('Trails', 'Playgrounds', 'Things To Do', 'Neighborhoods'),
                'future_filters' => array('Amenities', 'Neighborhood', 'Dog-friendly', 'Shade'),
                'related_pages' => array('Trails', 'Playgrounds', 'Family Activities', 'Things To Do'),
                'sidebar_recommendations' => array('Best parks for kids', 'Walking loops', 'Nearby dining'),
                'seo_strategy' => 'Optimize each park profile for local search and surrounding neighborhood intent.',
                'ai_strategy' => 'Structure park details into simple, scannable attributes and travel-intent summaries.'
            ),
            'trails' => array(
                'title' => 'Trails',
                'purpose' => 'Support walking, biking, and outdoor discovery through trail-focused content.',
                'audience' => 'Walkers, runners, cyclists, and outdoor enthusiasts.',
                'url' => '/trails/',
                'taxonomy' => 'Place',
                'categories' => array('Walking', 'Biking', 'Nature', 'Fitness'),
                'tags' => array('trails', 'walking', 'bike-routes'),
                'custom_fields' => array('Distance', 'Surface', 'Difficulty', 'Parking', 'Accessibility'),
                'schema_opportunities' => array('Trail', 'Place'),
                'internal_links' => array('Parks', 'Playgrounds', 'Things To Do', 'Neighborhoods'),
                'future_filters' => array('Length', 'Difficulty', 'Scenery', 'Accessibility'),
                'related_pages' => array('Parks', 'Playgrounds', 'Weekend Guide'),
                'sidebar_recommendations' => array('Trail highlights', 'Family-friendly routes', 'Nearby stops'),
                'seo_strategy' => 'Target trail and route-based related searches with strong location depth.',
                'ai_strategy' => 'Provide practical route details and quick “best for” summaries.'
            ),
            'playgrounds' => array(
                'title' => 'Playgrounds',
                'purpose' => 'Make family-friendly recreation easy to find and compare.',
                'audience' => 'Parents, caregivers, and families.',
                'url' => '/playgrounds/',
                'taxonomy' => 'Place',
                'categories' => array('Kids', 'Family', 'Outdoors', 'Recreation'),
                'tags' => array('playgrounds', 'kid-friendly', 'family'),
                'custom_fields' => array('Shade', 'Restrooms', 'Age range', 'Parking', 'Amenities'),
                'schema_opportunities' => array('Playground', 'Place'),
                'internal_links' => array('Parks', 'Family Activities', 'Schools', 'Neighborhoods'),
                'future_filters' => array('Shade', 'Age range', 'Water features', 'Neighborhood'),
                'related_pages' => array('Parks', 'Family Activities', 'Schools'),
                'sidebar_recommendations' => array('Best playgrounds', 'Nearby snacks', 'After-school ideas'),
                'seo_strategy' => 'Target local family and neighborhood queries related to playground access.',
                'ai_strategy' => 'Make playground details scannable and decision-friendly for parents.'
            ),
            'schools' => array(
                'title' => 'Schools',
                'purpose' => 'Provide a useful, trustworthy guide to local education options and school-related resources.',
                'audience' => 'Parents, families, and prospective residents.',
                'url' => '/schools/',
                'taxonomy' => 'Education',
                'categories' => array('Elementary', 'Middle', 'High', 'Private', 'Resources'),
                'tags' => array('schools', 'education', 'family-resources'),
                'custom_fields' => array('School type', 'Enrollment', 'Programs', 'Address', 'District info'),
                'schema_opportunities' => array('EducationalOrganization', 'School', 'LocalBusiness'),
                'internal_links' => array('Neighborhoods', 'New Resident Guide', 'Family Activities', 'Youth Sports'),
                'future_filters' => array('Grade level', 'Type', 'Programs', 'District'),
                'related_pages' => array('Neighborhoods', 'Family Activities', 'Youth Sports', 'New Resident Guide'),
                'sidebar_recommendations' => array('School resources', 'Family guides', 'Local events'),
                'seo_strategy' => 'Focus on school-related and relocation-intent queries with strong trust signals.',
                'ai_strategy' => 'Provide clear educational summaries, boundaries, and practical parent-focused details.'
            ),
            'churches' => array(
                'title' => 'Churches',
                'purpose' => 'Create a welcoming directory of faith communities and volunteer-friendly organizations.',
                'audience' => 'Residents, newcomers, families, and volunteers.',
                'url' => '/churches/',
                'taxonomy' => 'Community',
                'categories' => array('Faith', 'Service', 'Family', 'Community'),
                'tags' => array('churches', 'faith', 'community'),
                'custom_fields' => array('Service times', 'Denomination', 'Programs', 'Contact', 'Volunteer opportunities'),
                'schema_opportunities' => array('Place', 'Organization', 'LocalBusiness'),
                'internal_links' => array('Community Organizations', 'Volunteer', 'Neighborhoods', 'Events'),
                'future_filters' => array('Denomination', 'Service times', 'Family programs', 'Volunteer needs'),
                'related_pages' => array('Community Organizations', 'Volunteer', 'Events'),
                'sidebar_recommendations' => array('Volunteer opportunities', 'Community events', 'Service teams'),
                'seo_strategy' => 'Capture local faith-directory terms with trust-rich content and structured contact details.',
                'ai_strategy' => 'Make community purpose, service times, and volunteering clear and easy to parse.'
            ),
            'neighborhoods' => array(
                'title' => 'Neighborhoods',
                'purpose' => 'Help users understand the character and lifestyle of each neighborhood in South Forsyth.',
                'audience' => 'New movers, homebuyers, and local researchers.',
                'url' => '/neighborhoods/',
                'taxonomy' => 'Place',
                'categories' => array('Lifestyle', 'Real Estate', 'Schools', 'Dining'),
                'tags' => array('neighborhoods', 'local-lifestyle', 'moving'),
                'custom_fields' => array('Neighborhood name', 'Highlights', 'Schools', 'Amenities', 'Commute time'),
                'schema_opportunities' => array('Place', 'BreadcrumbList', 'LocalBusiness'),
                'internal_links' => array('New Resident Guide', 'Schools', 'Restaurants', 'Parks'),
                'future_filters' => array('Schools', 'Amenities', 'Commute', 'Lifestyle'),
                'related_pages' => array('New Resident Guide', 'Schools', 'Restaurants', 'Parks'),
                'sidebar_recommendations' => array('Move-in tips', 'Nearby amenities', 'Local favorites'),
                'seo_strategy' => 'Target neighborhood and relocation queries with strong local relevance and internal links.',
                'ai_strategy' => 'Present neighborhood summaries as practical guides that answer “what is it like to live there?”'
            ),
            'new-resident-guide' => array(
                'title' => 'New Resident Guide',
                'purpose' => 'Give new residents a quick-start guide to life in South Forsyth.',
                'audience' => 'New movers and people relocating to the area.',
                'url' => '/new-resident-guide/',
                'taxonomy' => 'Guide',
                'categories' => array('Moving', 'Essentials', 'Community', 'Resources'),
                'tags' => array('new-residents', 'moving', 'starter-guide'),
                'custom_fields' => array('Checklist', 'Neighborhood', 'Schools', 'Utilities', 'Services'),
                'schema_opportunities' => array('Article', 'HowTo', 'FAQPage'),
                'internal_links' => array('Neighborhoods', 'Schools', 'Healthcare', 'Government', 'Restaurants'),
                'future_filters' => array('Move-in stage', 'Family needs', 'Budget', 'Lifestyle'),
                'related_pages' => array('Neighborhoods', 'Schools', 'Healthcare', 'Government'),
                'sidebar_recommendations' => array('Essential services', 'Moving checklist', 'Local resources'),
                'seo_strategy' => 'Capture migration and relocation intent with evergreen, highly linkable content.',
                'ai_strategy' => 'Break the guide into clear sections and quick answers for everyday relocation questions.'
            ),
            'business-directory' => array(
                'title' => 'Business Directory',
                'purpose' => 'Create a trusted directory for the region’s businesses and service providers.',
                'audience' => 'Residents, visitors, and local business owners.',
                'url' => '/business-directory/',
                'taxonomy' => 'Directory',
                'categories' => array('Services', 'Retail', 'Professionals', 'Home Services'),
                'tags' => array('business-directory', 'local-business', 'services'),
                'custom_fields' => array('Category', 'Address', 'Phone', 'Hours', 'Website'),
                'schema_opportunities' => array('LocalBusiness', 'Organization', 'Offer'),
                'internal_links' => array('Restaurants', 'Shopping', 'Healthcare', 'Government'),
                'future_filters' => array('Category', 'Neighborhood', 'Rating', 'Open now'),
                'related_pages' => array('Restaurants', 'Shopping', 'Healthcare', 'Community Organizations'),
                'sidebar_recommendations' => array('Featured businesses', 'Popular categories', 'New listings'),
                'seo_strategy' => 'Use category-based landing pages and structured data to improve discoverability.',
                'ai_strategy' => 'Present each listing as a clear, factual business profile with helpful attributes.'
            ),
            'healthcare' => array(
                'title' => 'Healthcare',
                'purpose' => 'Organize healthcare and wellness resources for residents and families.',
                'audience' => 'Residents, seniors, and parents.',
                'url' => '/healthcare/',
                'taxonomy' => 'Health',
                'categories' => array('Primary Care', 'Urgent Care', 'Wellness', 'Dental'),
                'tags' => array('healthcare', 'wellness', 'medical-services'),
                'custom_fields' => array('Service type', 'Accepts new patients', 'Hours', 'Location', 'Insurance'),
                'schema_opportunities' => array('MedicalOrganization', 'LocalBusiness', 'FAQPage'),
                'internal_links' => array('Senior Resources', 'Family Activities', 'Government', 'Public Safety'),
                'future_filters' => array('Service type', 'Insurance', 'Emergency', 'Distance'),
                'related_pages' => array('Senior Resources', 'Public Safety', 'Government'),
                'sidebar_recommendations' => array('Urgent care', 'Wellness resources', 'Local clinics'),
                'seo_strategy' => 'Target service-based and location-based healthcare searches with strong local trust signals.',
                'ai_strategy' => 'Structure pages around practical questions such as hours, services, and when to seek care.'
            ),
            'senior-resources' => array(
                'title' => 'Senior Resources',
                'purpose' => 'Provide a helpful hub for seniors and caregivers looking for support, activities, and services.',
                'audience' => 'Seniors, caregivers, and family members.',
                'url' => '/senior-resources/',
                'taxonomy' => 'Community',
                'categories' => array('Support', 'Activities', 'Health', 'Transportation'),
                'tags' => array('seniors', 'caregivers', 'resources'),
                'custom_fields' => array('Program type', 'Age group', 'Location', 'Accessibility', 'Contact'),
                'schema_opportunities' => array('Organization', 'FAQPage', 'LocalBusiness'),
                'internal_links' => array('Healthcare', 'Volunteer', 'Community Organizations', 'Neighborhoods'),
                'future_filters' => array('Service area', 'Accessibility', 'Activity type', 'Support level'),
                'related_pages' => array('Healthcare', 'Volunteer', 'Community Organizations'),
                'sidebar_recommendations' => array('Local support', 'Caregiver resources', 'Senior events'),
                'seo_strategy' => 'Focus on practical-resource queries and supportive local community information.',
                'ai_strategy' => 'Provide clear eligibility and support details for better retrieval and answer generation.'
            ),
            'family-activities' => array(
                'title' => 'Family Activities',
                'purpose' => 'Make it easy for families to find ideas and seasonal options that match their lifestyle.',
                'audience' => 'Parents, families, and caregivers.',
                'url' => '/family-activities/',
                'taxonomy' => 'Activity',
                'categories' => array('Indoor', 'Outdoor', 'Educational', 'Weekend'),
                'tags' => array('family', 'activities', 'kid-friendly'),
                'custom_fields' => array('Age range', 'Weather suitability', 'Cost', 'Duration'),
                'schema_opportunities' => array('Event', 'ThingToDo', 'FAQPage'),
                'internal_links' => array('Things To Do', 'Parks', 'Playgrounds', 'Schools'),
                'future_filters' => array('Age range', 'Indoor/Outdoor', 'Budget', 'Weather'),
                'related_pages' => array('Things To Do', 'Parks', 'Schools', 'Youth Sports'),
                'sidebar_recommendations' => array('Weekend ideas', 'Rainy-day picks', 'Seasonal activities'),
                'seo_strategy' => 'Target family-related local queries and child-focused experiences.',
                'ai_strategy' => 'Make activity suggestions easy to compare and understand quickly.'
            ),
            'youth-sports' => array(
                'title' => 'Youth Sports',
                'purpose' => 'Connect families to youth sports opportunities and athletic programming.',
                'audience' => 'Parents, kids, coaches, and community volunteers.',
                'url' => '/youth-sports/',
                'taxonomy' => 'Sports',
                'categories' => array('Soccer', 'Baseball', 'Basketball', 'Programs'),
                'tags' => array('youth-sports', 'athletics', 'kids'),
                'custom_fields' => array('Sport', 'Season', 'Age group', 'Location', 'Registration'),
                'schema_opportunities' => array('SportsEvent', 'Organization', 'Event'),
                'internal_links' => array('Schools', 'Family Activities', 'Events', 'Volunteer'),
                'future_filters' => array('Sport', 'Season', 'Age group', 'Location'),
                'related_pages' => array('Schools', 'Family Activities', 'Events'),
                'sidebar_recommendations' => array('Registration deadlines', 'Season overview', 'Volunteer opportunities'),
                'seo_strategy' => 'Capture sport-specific and seasonal searches with structured content and local relevance.',
                'ai_strategy' => 'Make registration, season, and location details easy to retrieve.'
            ),
            'shopping' => array(
                'title' => 'Shopping',
                'purpose' => 'Create a guide for retail, boutiques, and everyday shopping needs.',
                'audience' => 'Residents and visitors.',
                'url' => '/shopping/',
                'taxonomy' => 'Commerce',
                'categories' => array('Retail', 'Groceries', 'Boutiques', 'Home Goods'),
                'tags' => array('shopping', 'retail', 'local-businesses'),
                'custom_fields' => array('Category', 'Hours', 'Location', 'Specialties', 'Parking'),
                'schema_opportunities' => array('LocalBusiness', 'Offer', 'Store'),
                'internal_links' => array('Restaurants', 'Business Directory', 'Weekend Guide', 'Neighborhoods'),
                'future_filters' => array('Category', 'Neighborhood', 'Open now', 'Price range'),
                'related_pages' => array('Restaurants', 'Business Directory', 'Neighborhoods'),
                'sidebar_recommendations' => array('Best local shops', 'Weekend errands', 'New stores'),
                'seo_strategy' => 'Target SHOPPING and local retail discovery terms with profile-rich listings.',
                'ai_strategy' => 'Highlight practical content like hours, specialties, and what each shop is known for.'
            ),
            'history' => array(
                'title' => 'History',
                'purpose' => 'Preserve and share the local story of South Forsyth through historical context and heritage pieces.',
                'audience' => 'Residents, researchers, and history-curious readers.',
                'url' => '/history/',
                'taxonomy' => 'History',
                'categories' => array('Local History', 'Heritage', 'Culture', 'People'),
                'tags' => array('history', 'heritage', 'local-story'),
                'custom_fields' => array('Date', 'Source', 'Location', 'People involved', 'Photos'),
                'schema_opportunities' => array('Article', 'BreadcrumbList', 'ImageObject'),
                'internal_links' => array('Neighborhoods', 'Local News', 'Seasonal Guides', 'Holiday Guides'),
                'future_filters' => array('Era', 'People', 'Place', 'Theme'),
                'related_pages' => array('Neighborhoods', 'Local News', 'Holiday Guides'),
                'sidebar_recommendations' => array('Featured heritage stories', 'Historic landmarks', 'Related articles'),
                'seo_strategy' => 'Target historical and heritage intent with evergreen storytelling and strong internal links.',
                'ai_strategy' => 'Use contextual summaries and related links to support knowledge discovery.'
            ),
            'volunteer' => array(
                'title' => 'Volunteer',
                'purpose' => 'Make volunteering approachable and clearly connected to local needs.',
                'audience' => 'Volunteers, nonprofits, and community-minded residents.',
                'url' => '/volunteer/',
                'taxonomy' => 'Community',
                'categories' => array('Service', 'Events', 'Schools', 'Nonprofit'),
                'tags' => array('volunteer', 'service', 'community'),
                'custom_fields' => array('Cause', 'Time commitment', 'Age range', 'Contact', 'Location'),
                'schema_opportunities' => array('Organization', 'Event', 'FAQPage'),
                'internal_links' => array('Community Organizations', 'Churches', 'Events', 'Schools'),
                'future_filters' => array('Cause', 'Availability', 'Location', 'Skill'),
                'related_pages' => array('Community Organizations', 'Churches', 'Events'),
                'sidebar_recommendations' => array('Volunteer opportunities', 'Upcoming service days', 'Partner groups'),
                'seo_strategy' => 'Aim for service and community involvement queries tied to local impact.',
                'ai_strategy' => 'Surface clear calls to action, timing, and fit for different audiences.'
            ),
            'community-organizations' => array(
                'title' => 'Community Organizations',
                'purpose' => 'Highlight the nonprofits, associations, and civic groups shaping local life.',
                'audience' => 'Residents, volunteers, and civic-minded readers.',
                'url' => '/community-organizations/',
                'taxonomy' => 'Community',
                'categories' => array('Nonprofit', 'Civic', 'Arts', 'Youth'),
                'tags' => array('community-organizations', 'nonprofits', 'civic'),
                'custom_fields' => array('Mission', 'Focus area', 'Contact', 'Volunteer needs', 'Events'),
                'schema_opportunities' => array('Organization', 'LocalBusiness'),
                'internal_links' => array('Volunteer', 'Churches', 'Events', 'Local News'),
                'future_filters' => array('Cause', 'Audience', 'Location', 'Volunteer needs'),
                'related_pages' => array('Volunteer', 'Churches', 'Local News'),
                'sidebar_recommendations' => array('Featured organizations', 'Upcoming collaboration events', 'How to get involved'),
                'seo_strategy' => 'Target “community organizations near me” and nonprofit discovery intent.',
                'ai_strategy' => 'Make mission, impact, and involvement pathways easy to understand.'
            ),
            'public-safety' => array(
                'title' => 'Public Safety',
                'purpose' => 'Provide calm, reliable information about safety resources and community alerts.',
                'audience' => 'Residents, families, and visitors.',
                'url' => '/public-safety/',
                'taxonomy' => 'Safety',
                'categories' => array('Emergency', 'Preparedness', 'Crime', 'Neighborhood'),
                'tags' => array('public-safety', 'emergency-preparedness', 'safety'),
                'custom_fields' => array('Contact', 'Emergency instructions', 'Neighborhood alerts', 'Resources'),
                'schema_opportunities' => array('FAQPage', 'Article', 'Organization'),
                'internal_links' => array('Government', 'Traffic', 'Weather', 'Local News'),
                'future_filters' => array('Topic', 'Emergency type', 'Neighborhood', 'Urgency'),
                'related_pages' => array('Government', 'Weather', 'Traffic', 'Local News'),
                'sidebar_recommendations' => array('Emergency contacts', 'Neighborhood alerts', 'Weather and traffic updates'),
                'seo_strategy' => 'Prioritize clarity, trust, and urgency with evergreen safety information.',
                'ai_strategy' => 'Format as concise answers with actionable steps and contacts.'
            ),
            'government' => array(
                'title' => 'Government',
                'purpose' => 'Create a civic hub connecting residents to public services and local governance.',
                'audience' => 'Residents, business owners, and civic-minded readers.',
                'url' => '/government/',
                'taxonomy' => 'Civic',
                'categories' => array('Services', 'Officials', 'Public Records', 'Meetings'),
                'tags' => array('government', 'civic', 'public-services'),
                'custom_fields' => array('Department', 'Contact', 'Meeting schedule', 'Hours', 'Forms'),
                'schema_opportunities' => array('GovernmentOrganization', 'FAQPage', 'Organization'),
                'internal_links' => array('Public Safety', 'Traffic', 'Weather', 'Local News'),
                'future_filters' => array('Department', 'Service type', 'Meeting date', 'Audience'),
                'related_pages' => array('Public Safety', 'Traffic', 'Weather', 'Local News'),
                'sidebar_recommendations' => array('Service links', 'Meeting calendar', 'Important contacts'),
                'seo_strategy' => 'Target public-service and civic information queries with official, easy-to-follow content.',
                'ai_strategy' => 'Give clear, direct answers about services, contacts, and procedures.'
            ),
            'local-news' => array(
                'title' => 'Local News',
                'purpose' => 'Serve as the home for timely community updates, stories, and public information.',
                'audience' => 'Residents, parents, and local readers.',
                'url' => '/local-news/',
                'taxonomy' => 'News',
                'categories' => array('Community', 'Education', 'Government', 'Business', 'Events'),
                'tags' => array('news', 'local-updates', 'community'),
                'custom_fields' => array('Publish date', 'Author', 'Location', 'Category', 'Related links'),
                'schema_opportunities' => array('Article', 'NewsArticle', 'BreadcrumbList'),
                'internal_links' => array('Events', 'Government', 'Weather', 'Traffic', 'Seasonal Guides'),
                'future_filters' => array('Category', 'Date', 'Topic', 'Audience'),
                'related_pages' => array('Events', 'Government', 'Weather', 'Traffic'),
                'sidebar_recommendations' => array('Latest stories', 'Popular topics', 'Featured updates'),
                'seo_strategy' => 'Use timely evergreen news content with clear headlines, metadata, and internal linking.',
                'ai_strategy' => 'Structure stories for quick summarization and topical association across related pages.'
            ),
            'weather' => array(
                'title' => 'Weather',
                'purpose' => 'Provide practical weather context for planning and day-to-day local life.',
                'audience' => 'Residents, commuters, families, and event planners.',
                'url' => '/weather/',
                'taxonomy' => 'Weather',
                'categories' => array('Forecast', 'Alerts', 'Seasonal', 'Travel'),
                'tags' => array('weather', 'forecast', 'local-conditions'),
                'custom_fields' => array('Forecast date', 'Alert level', 'Impact', 'Recommended actions'),
                'schema_opportunities' => array('Article', 'FAQPage', 'Weather'),
                'internal_links' => array('Traffic', 'Events', 'Seasonal Guides', 'Holiday Guides'),
                'future_filters' => array('Forecast period', 'Alerts', 'Impact', 'Season'),
                'related_pages' => array('Traffic', 'Events', 'Seasonal Guides'),
                'sidebar_recommendations' => array('Forecast summary', 'Event impact', 'Outdoor plans'),
                'seo_strategy' => 'Target weather and plan-ahead queries with local relevance and modern structured data.',
                'ai_strategy' => 'Make weather advice actionable and easy to summarize for everyday decision-making.'
            ),
            'traffic' => array(
                'title' => 'Traffic',
                'purpose' => 'Keep residents informed about commute conditions, delays, and local travel updates.',
                'audience' => 'Commuters, parents, and event-goers.',
                'url' => '/traffic/',
                'taxonomy' => 'Transportation',
                'categories' => array('Commute', 'Road Conditions', 'Construction', 'Alerts'),
                'tags' => array('traffic', 'commute', 'travel'),
                'custom_fields' => array('Route', 'Delay level', 'Impact', 'Time updated'),
                'schema_opportunities' => array('Article', 'FAQPage', 'Event'),
                'internal_links' => array('Weather', 'Government', 'Events', 'Local News'),
                'future_filters' => array('Route', 'Severity', 'Time', 'Area'),
                'related_pages' => array('Weather', 'Government', 'Local News'),
                'sidebar_recommendations' => array('Traffic alerts', 'Road conditions', 'Route alternatives'),
                'seo_strategy' => 'Prioritize practical, local travel and route information.',
                'ai_strategy' => 'Provide concise, time-sensitive updates that answer commuter questions directly.'
            ),
            'seasonal-guides' => array(
                'title' => 'Seasonal Guides',
                'purpose' => 'Offer timely seasonal planning for the most relevant local experiences.',
                'audience' => 'Residents, families, and visitors.',
                'url' => '/seasonal-guides/',
                'taxonomy' => 'Guide',
                'categories' => array('Spring', 'Summer', 'Fall', 'Winter'),
                'tags' => array('seasonal-guide', 'planning', 'local-experiences'),
                'custom_fields' => array('Season', 'Recommended activities', 'Weather notes', 'Events'),
                'schema_opportunities' => array('Article', 'HowTo', 'BreadcrumbList'),
                'internal_links' => array('Weekend Guide', 'Events', 'Things To Do', 'Holiday Guides'),
                'future_filters' => array('Season', 'Audience', 'Activity type', 'Budget'),
                'related_pages' => array('Weekend Guide', 'Events', 'Holiday Guides'),
                'sidebar_recommendations' => array('Seasonal highlights', 'Family plans', 'Event tie-ins'),
                'seo_strategy' => 'Target seasonal planning and annual-intent queries with evergreen updateable content.',
                'ai_strategy' => 'Make seasonal recommendations easy to browse and digest in a structured way.'
            ),
            'holiday-guides' => array(
                'title' => 'Holiday Guides',
                'purpose' => 'Create rich, shareable planning content around local holiday moments and traditions.',
                'audience' => 'Families, visitors, and local event planners.',
                'url' => '/holiday-guides/',
                'taxonomy' => 'Guide',
                'categories' => array('Holidays', 'Seasonal', 'Family', 'Events'),
                'tags' => array('holiday-guide', 'seasonal-planning', 'local-traditions'),
                'custom_fields' => array('Holiday', 'Date', 'Activities', 'Parking', 'Events'),
                'schema_opportunities' => array('Article', 'Event', 'FAQPage'),
                'internal_links' => array('Seasonal Guides', 'Events', 'Weekend Guide', 'Things To Do'),
                'future_filters' => array('Holiday', 'Season', 'Audience', 'Budget'),
                'related_pages' => array('Seasonal Guides', 'Events', 'Weekend Guide'),
                'sidebar_recommendations' => array('Holiday events', 'Family activities', 'Traffic and weather notes'),
                'seo_strategy' => 'Target holiday and event planning queries with strong seasonal relevance and internal links.',
                'ai_strategy' => 'Organize holiday information around practical decision points and itinerary prompts.'
            )
        );
    }
}

if (! function_exists('southforsyth_get_section_definition')) {
    function southforsyth_get_section_definition($slug)
    {
        $architecture = southforsyth_get_information_architecture();

        return $architecture[$slug] ?? array(
            'title' => ucfirst(str_replace('-', ' ', $slug)),
            'purpose' => 'Add a purpose statement for this section.',
            'audience' => 'Define the audience for this section.',
            'url' => '/' . $slug . '/',
            'taxonomy' => 'Topic',
            'categories' => array('General'),
            'tags' => array('local-guide'),
            'custom_fields' => array('Title', 'Summary', 'Location', 'Related links'),
            'schema_opportunities' => array('Article'),
            'internal_links' => array('Home'),
            'future_filters' => array('Category'),
            'related_pages' => array('Home'),
            'sidebar_recommendations' => array('Related content'),
            'seo_strategy' => 'Create a clear, topical page focused on one primary search intent.',
            'ai_strategy' => 'Use concise summaries, FAQs, and structured metadata for improved retrieval.'
        );
    }
}
